name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check Hello World
      id: check-hello-world
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check Hello World
        setup-command: ''
        command: python3 -c "from hello import say_hello; assert say_hello().strip() == 'Hello World'"
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        runners: check-hello-world
      env:
        CHECK-HELLO-WORLD_RESULTS: "${{steps.check-hello-world.outputs.result}}"
